apiVersion: integration/v1
kind: Integration
name: victorops
channel: alpha
version: v20200522
summary: Relay integration for VictorOps
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-victorops

description: |
  This integration provides access to VictorOps, a real-time operations and
  incident response platform.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- rto
- incident response
