# Step metadata example - full description at:
# https://github.com/puppetlabs/relay-rfcs/blob/master/content/0006-integration-layout/rfc.md#common-metadata
apiVersion: integration/v1
kind: Step
name: incident-update
version: 1
summary: Update a Splunk On-Call incident timeline

description: |
  Updates a Splunk On-Call incident timeline with data.

publish:
  repository: relaysh/splunkoncall-step-incident-update

build:
  apiVersion: build/v1
  kind: Docker

# optional list of examples; each one can be a Step or a complete Workflow
examples:
- summary: Example usage for the step
  content:
    apiVersion: v1
    kind: Step
    image: relaysh/splunkoncall-step-incident-update
    spec:
      endpointURL: ${secrets.endpointURL}
      routingKey: relay
      entityID: ""
      entityDisplayName: ${parameters.entityDisplayName}
      stateMessage: ${parameters.stateMessage}

schemas:
  spec:
    source: file
    file: spec.schema.json
