apiVersion: container/v1
kind: StepContainer
name: splunkoncall-trigger-incident-triggered
inherit: {from: sdk, name: python.v1}
title: Splunk On-Call incident triggered
description: >
  This trigger fires when a Splunk On-Call incident is triggered for the first time.
settings:
  CommandPath: handler.py
  AdditionalPythonPackages:
  - quart
