apiVersion: integration/v1
kind: Trigger
name: incident-triggered
version: 1
summary: Splunk On-Call incident triggered
description: |
  This trigger fires when a Splunk On-Call incident is triggered for the first time.

responders:
- webhook

schemas:
  spec: {}
  event:
    source: file
    file: event.schema.json

examples:
- summary: Receive a webhook from Splunk On-Call when an incident is created
  content:
    apiVersion: v1
    kind: Trigger
    name: splunkoncall-incident
    source:
      type: webhook
      image: relaysh/splunkoncall-trigger-incident-triggered:latest
    binding:
      parameters:
        id: ${event.alert.entity_id}
        name: ${event.alert.entity_display_name}
        state: ${event.alert.entity_state}
        timestamp: ${event.alert.vo_alert_rcv_time}

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/splunkoncall-trigger-incident-triggered
